### PR TITLE
Tax percentage

### PR DESCRIPTION
**Pull request by downsider**
Introduced "tax percent" field for invoice and subscription APIs

### CODE REVIEW

**Comment by jlinn** [comment]
Awesome.  Thanks!

**Comment by downsider** [comment]
No problem :)

Could you create a release tag for this please (1.3.0 or similar)?
I can use the master branch in my project for now, but I much prefer using distinct releases.

Thanks

**Comment by jlinn** [comment]
I'll create a new tag after I fix the currently failing tests.  I should be able to get to that some time this weekend.

**Comment by downsider** [comment]
Thanks

**Comment by downsider** [comment]
Hey @jlinn

Sorry to re-open this thread, but I've got an issue with the 1.3 release that is related to this PR.
As it turns out, I didn't update to the 1.3 release until just now, so I was unaware of the bug that has been introduced. 

To cut a long story short, the change you made to refactor "cards" to "sources" has broken my application. Would you be able to tag the commit before that (where my PR was accepted) with 1.2.1 please, so that I can continue using the API while I update my app to use "sources"?

Unfortunately, this isn't a trivial change for me; the version of the Stripe API we're using is so old it still uses "cards" and updating to the latest version is a massive update affecting a large portion of the codebase.

I appreciate this is an unusual request, but I would be very appreciative if you could accommodate me.

Thanks

**Comment by jlinn** [comment]
Sure, no problem.  I just created [v1.2.1](https://github.com/jlinn/stripe-api-php/releases/tag/v1.2.1). Hopefully, that will work for you.

**Comment by downsider** [comment]
Thank you! :)

**Pull request merged**
